# This is a config for E2B sandbox template.
# You can use template ID (a3bxfzfrrard093pqr9t) or template name (neodev-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("neodev-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("neodev-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('neodev-nextjs-test')

team_id = "82097f03-f623-4b14-a357-f7eb43fe15d4"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "neodev-nextjs-test"
template_id = "a3bxfzfrrard093pqr9t"
